CREATE DATABASE IF NOT EXISTS meeting_scheduler;
USE meeting_scheduler;
CREATE TABLE IF NOT EXISTS users(id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100) NOT NULL,email VARCHAR(150) UNIQUE NOT NULL,password VARCHAR(255) NOT NULL,role ENUM('admin','user') DEFAULT 'user');
CREATE TABLE IF NOT EXISTS members(id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100) NOT NULL);
CREATE TABLE IF NOT EXISTS availability(id INT AUTO_INCREMENT PRIMARY KEY,member_id INT NOT NULL,available_from TIME NOT NULL,available_to TIME NOT NULL,FOREIGN KEY(member_id) REFERENCES members(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS bookings(id INT AUTO_INCREMENT PRIMARY KEY,user_id INT NOT NULL,member_id INT NOT NULL,slot_id INT NOT NULL,reason TEXT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(member_id) REFERENCES members(id) ON DELETE CASCADE,FOREIGN KEY(slot_id) REFERENCES availability(id) ON DELETE CASCADE);